export const seedMovies = [
 {id:'interstellar',title:'Interstellar',originalTitle:'Interstellar',year:2014,runtime:169,genres:['Ficção científica','Drama'],director:'Christopher Nolan',communityRating:8.7,userRating:9.5,status:'watched',favorite:true,watchedCount:2,watchedDates:['2026-08-14'],review:'Uma experiência que cresce a cada revisita. A trilha e o silêncio do espaço ainda me deixam sem ar.',notes:'Cena favorita: o reencontro pelas mensagens.\nFrase: “Love is the one thing that transcends time and space.”',tags:['obra-prima','ficção-científica','reassistir'],poster:'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',backdrop:'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg'},
 {id:'past-lives',title:'Vidas Passadas',originalTitle:'Past Lives',year:2023,runtime:106,genres:['Romance','Drama'],director:'Celine Song',communityRating:7.8,userRating:8.5,status:'watched',favorite:true,watchedCount:1,watchedDates:['2026-07-22'],review:'Delicado, maduro e dolorosamente honesto.',notes:'A conversa no bar é perfeita.',tags:['conforto'],poster:'https://image.tmdb.org/t/p/w780/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',backdrop:'https://image.tmdb.org/t/p/original/3sv07MEJsHj1VYTD0wk6MPNQ82E.jpg'},
 {id:'dune2',title:'Duna: Parte Dois',originalTitle:'Dune: Part Two',year:2024,runtime:166,genres:['Ficção científica','Aventura'],director:'Denis Villeneuve',communityRating:8.5,userRating:9,status:'watched',favorite:false,watchedCount:1,watchedDates:['2026-05-08'],review:'Escala monumental sem perder o peso emocional.',notes:'O desenho de som é absurdo.',tags:['épico'],poster:'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',backdrop:'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg'},
 {id:'inception',title:'A Origem',originalTitle:'Inception',year:2010,runtime:148,genres:['Ação','Ficção científica'],director:'Christopher Nolan',communityRating:8.8,userRating:null,status:'watchlist',favorite:false,watchedCount:0,watchedDates:[],review:'',notes:'Quero rever prestando atenção nos níveis do sonho.',tags:['reassistir'],poster:'https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',backdrop:'https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg'},
 {id:'perfect-days',title:'Dias Perfeitos',originalTitle:'Perfect Days',year:2023,runtime:124,genres:['Drama'],director:'Wim Wenders',communityRating:8.0,userRating:null,status:'watchlist',favorite:false,watchedCount:0,watchedDates:[],review:'',notes:'',tags:['conforto'],poster:'https://image.tmdb.org/t/p/w780/1qwiPbRghYPOhQZqR8cS6J5h6sG.jpg',backdrop:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1800&q=85'},
 {id:'arrival',title:'A Chegada',originalTitle:'Arrival',year:2016,runtime:116,genres:['Ficção científica','Mistério'],director:'Denis Villeneuve',communityRating:8.0,userRating:8,status:'watched',favorite:false,watchedCount:1,watchedDates:['2026-03-12'],review:'Uma ficção científica íntima e muito humana.',notes:'',tags:['ficção-científica'],poster:'https://image.tmdb.org/t/p/w780/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',backdrop:'https://image.tmdb.org/t/p/original/5T4iwC6JjTv7T9vYzvU5J5os6xJ.jpg'}
];
export const seedMarathons = [{id:'nolan',title:'A mente de Nolan',description:'Uma viagem por tempo, memória e grandes telas.',cover:'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',movieIds:['interstellar','inception'],accent:'#dc5d54'}];
